version: '3.9'

services:
  mysql:
    image: mysql
    container_name: mysql-spring
    restart: always
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'spring'
      MYSQL_ROOT_PASSWORD: 'user'
      MYSQL_USER: 'user'
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 4000:8080
